<?php

/**
 * Add items to queue
 */
function facebook_video_add_queue_items()
{
    // Invoke facebook_video.default service
    $facebookVideoService = \Drupal::service('facebook_video.default');

    // Fetch list of nodes
    $nodes = $facebookVideoService->fetchNodes();

    $queueService = \Drupal::service('queue');
    $queue = $queueService->get('facebook-video-processing');

    // Loop through nodes and add them to the queue
    foreach ($nodes as $node)
    {
        // Retrieve the fields we will pass along with each queue item
        $field_fb_page_id = $node->get('field_fb_page_id')->getValue();
        $field_fb_video_id = $node->get('field_fb_video_id')->getValue();
        $nid = $node->id();

        // Create queue item
        $queue->createItem([
            $nid,
            $field_fb_page_id[0]['value'],
            $field_fb_video_id[0]['value']
        ]);
    }
}
